# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS builder

WORKDIR /app

COPY docs/package.json docs/package-lock.json ./docs/
RUN cd docs && npm ci

COPY docs ./docs

RUN cd docs && npm run build


FROM nginxinc/nginx-unprivileged:1.27-alpine AS runtime

COPY docs/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/docs/.vitepress/dist /usr/share/nginx/html

EXPOSE 8080

