export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  header: {
    position: 'sticky' as const,
    top: 0,
    zIndex: 100,
    height: '72px',
    boxSizing: 'border-box' as const,
    background: 'rgba(14, 14, 14, 0.86)',
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid rgba(255,255,255,0.10)',
    padding: '14px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logo: {
    fontSize: '24px',
    fontWeight: 900,
    color: '#fff',
    letterSpacing: '-0.01em',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    textShadow: '0 10px 30px rgba(0,0,0,0.55)',
  },
  stats: {
    display: 'flex',
    gap: '24px',
  },
  stat: {
    textAlign: 'center' as const,
  },
  statValue: {
    fontSize: '20px',
    fontWeight: 600,
    color: '#fff',
  },
  statLabel: {
    fontSize: '12px',
    color: '#888',
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  stickyNav: {
    position: 'sticky' as const,
    top: '72px',
    zIndex: 80,
    background: 'rgba(12, 12, 12, 0.86)',
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid rgba(255,255,255,0.10)',
  },
  tabs: {
    display: 'flex',
    background: 'transparent',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
  },
  tab: {
    padding: '12px 24px',
    cursor: 'pointer',
    border: 'none',
    background: 'transparent',
    color: '#888',
    fontSize: '14px',
    fontWeight: 500,
    borderBottom: '2px solid transparent',
  },
  tabActive: {
    color: '#fff',
    borderBottomColor: '#6366f1',
  },
  toolbar: {
    padding: '12px 24px',
    background: 'transparent',
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  select: {
    padding: '8px 12px',
    background: '#252525',
    border: '1px solid #333',
    borderRadius: '6px',
    color: '#fff',
    fontSize: '14px',
    outline: 'none',
  },
  searchInput: {
    flex: 1,
    padding: '8px 12px',
    background: '#252525',
    border: '1px solid #333',
    borderRadius: '6px',
    color: '#fff',
    fontSize: '14px',
    outline: 'none',
  },
  button: {
    padding: '8px 16px',
    background: '#333',
    border: 'none',
    borderRadius: '6px',
    color: '#fff',
    cursor: 'pointer',
    fontSize: '14px',
  },
  buttonDanger: {
    background: '#7f1d1d',
  },
  liveIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    color: '#22c55e',
  },
  liveDot: {
    width: '8px',
    height: '8px',
    background: '#22c55e',
    borderRadius: '50%',
    animation: 'pulse 2s infinite',
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 10px',
    borderRadius: '999px',
    border: '1px solid #333',
    background: '#111',
    fontSize: '12px',
    color: '#bbb',
  },
  badgeOutline: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 10px',
    borderRadius: '999px',
    border: '1px solid #333',
    background: '#0f0f0f',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.02em',
  },
  badgeView: {
    borderColor: '#14532d',
    color: '#4ade80',
    background: '#052e16',
  },
  badgeEdit: {
    borderColor: '#3730a3',
    color: '#c7d2fe',
    background: '#111827',
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 8px',
    borderRadius: '999px',
    border: '1px solid #333',
    background: '#0f0f0f',
    fontSize: '12px',
    color: '#ddd',
  },
  chipButton: {
    background: 'transparent',
    border: 'none',
    color: '#888',
    cursor: 'pointer',
    padding: 0,
    fontSize: '12px',
    lineHeight: 1,
  },
  filtersPanel: {
    margin: '0 24px',
    marginTop: '12px',
    padding: '14px 16px',
    borderRadius: '10px',
    border: '1px solid #333',
    background: '#121212',
  },
  filtersGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '12px',
  },
  filterCard: {
    border: '1px solid #2a2a2a',
    background: '#0f0f0f',
    borderRadius: '10px',
    padding: '12px',
  },
  filterCardTitle: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: '10px',
    marginBottom: '10px',
    color: '#ddd',
    fontSize: '12px',
    fontWeight: 700,
  },
  filterHint: {
    color: '#777',
    fontSize: '11px',
    fontWeight: 500,
    whiteSpace: 'nowrap' as const,
  },
  filterValues: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '8px',
    alignItems: 'center',
  },
  filterInput: {
    width: '100%',
    padding: '8px 10px',
    background: '#151515',
    border: '1px solid #333',
    borderRadius: '8px',
    color: '#fff',
    fontSize: '13px',
    outline: 'none',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: '16px 24px',
    background: '#0b0b0b',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
  },
  th: {
    position: 'sticky' as const,
    top: 0,
    zIndex: 5,
    textAlign: 'left' as const,
    padding: '12px',
    borderBottom: '1px solid #333',
    background: '#0b0b0b',
    color: '#888',
    fontSize: '12px',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
  },
  td: {
    padding: '12px',
    borderBottom: '1px solid #222',
    fontSize: '13px',
  },
  row: {
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  badge: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 600,
  },
  badgeSuccess: {
    background: '#14532d',
    color: '#4ade80',
  },
  badgeError: {
    background: '#7f1d1d',
    color: '#fca5a5',
  },
  mono: {
    fontFamily: 'Monaco, Consolas, monospace',
    fontSize: '12px',
    color: '#a78bfa',
  },
  modal: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(0,0,0,0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
    zIndex: 1000,
  },
  modalContent: {
    background: '#1a1a1a',
    borderRadius: '12px',
    maxWidth: '1000px',
    width: '100%',
    maxHeight: '85vh',
    overflow: 'hidden',
    border: '1px solid #333',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  modalSmallContent: {
    background: '#1a1a1a',
    borderRadius: '12px',
    maxWidth: '520px',
    width: '100%',
    maxHeight: '85vh',
    overflow: 'hidden',
    border: '1px solid #333',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  modalHeader: {
    padding: '16px 24px',
    borderBottom: '1px solid #333',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexShrink: 0,
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: 600,
    color: '#fff',
  },
  modalActions: {
    display: 'flex',
    gap: '8px',
  },
  modalBody: {
    padding: '24px',
    overflow: 'auto',
    flex: 1,
  },
  metaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
    marginBottom: '24px',
  },
  metaItem: {
    background: '#252525',
    padding: '12px',
    borderRadius: '8px',
  },
  metaLabel: {
    fontSize: '11px',
    color: '#888',
    textTransform: 'uppercase' as const,
    marginBottom: '4px',
  },
  metaValue: {
    fontSize: '14px',
    color: '#fff',
    fontFamily: 'Monaco, Consolas, monospace',
    wordBreak: 'break-all' as const,
  },
  jsonContainer: {
    background: '#0a0a0a',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  jsonHeader: {
    padding: '12px 16px',
    background: '#151515',
    borderBottom: '1px solid #333',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  jsonTitle: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#888',
    textTransform: 'uppercase' as const,
  },
  jsonBody: {
    padding: '16px',
    overflow: 'auto',
    maxHeight: '400px',
  },
  inspectorTabs: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  inspectorTab: {
    padding: '4px 8px',
    borderRadius: '6px',
    border: '1px solid #333',
    background: '#0f0f0f',
    color: '#bbb',
    cursor: 'pointer',
    fontSize: '11px',
  },
  inspectorTabActive: {
    borderColor: '#6366f1',
    color: '#fff',
    background: '#1b1b3a',
  },
  split: {
    display: 'flex',
    gap: '16px',
    alignItems: 'stretch',
  },
  pane: {
    flex: 1,
    minWidth: 0,
    background: '#141414',
    border: '1px solid #333',
    borderRadius: '10px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  paneHeader: {
    padding: '10px 12px',
    borderBottom: '1px solid #333',
    background: '#101010',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '10px',
  },
  paneTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#ddd',
    textTransform: 'uppercase' as const,
  },
  paneBody: {
    padding: '10px 12px',
    overflow: 'auto',
    flex: 1,
  },
  treeRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    padding: '2px 0',
    fontFamily: 'Monaco, Consolas, monospace',
    fontSize: '12px',
    lineHeight: 1.6,
    whiteSpace: 'pre' as const,
  },
  treeToggle: {
    width: '18px',
    background: 'transparent',
    border: 'none',
    color: '#888',
    cursor: 'pointer',
    padding: 0,
    textAlign: 'center' as const,
  },
  treeKey: {
    color: '#60a5fa',
  },
  treeType: {
    color: '#888',
  },
  treeValueString: {
    color: '#4ade80',
  },
  treeValueNumber: {
    color: '#a78bfa',
  },
  treeValueBool: {
    color: '#f472b6',
  },
  treeValueNull: {
    color: '#888',
  },
  spanRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 90px 70px',
    gap: '10px',
    alignItems: 'center',
    padding: '6px 8px',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  spanRowSelected: {
    background: '#1b1b3a',
    border: '1px solid #2f2f68',
  },
  spanName: {
    fontFamily: 'Monaco, Consolas, monospace',
    fontSize: '12px',
    color: '#e5e7eb',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  spanMeta: {
    fontSize: '12px',
    color: '#999',
    textAlign: 'right' as const,
  },
  barTrack: {
    height: '6px',
    background: '#0a0a0a',
    border: '1px solid #222',
    borderRadius: '999px',
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    background: '#6366f1',
  },
  dashboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(12, 1fr)',
    gap: '12px',
    alignItems: 'stretch',
  },
  card: {
    background: '#141414',
    border: '1px solid #333',
    borderRadius: '12px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: 0,
  },
  cardHeader: {
    padding: '10px 12px',
    borderBottom: '1px solid #333',
    background: '#101010',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '10px',
  },
  cardTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#e5e7eb',
    textTransform: 'uppercase' as const,
  },
  cardBody: {
    padding: '12px',
    flex: 1,
    overflow: 'auto',
  },
  tiny: {
    fontSize: '11px',
    color: '#888',
  },
  barRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 70px',
    gap: '10px',
    alignItems: 'center',
    padding: '6px 0',
  },
  barLabel: {
    fontFamily: 'Monaco, Consolas, monospace',
    fontSize: '12px',
    color: '#e5e7eb',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  barValue: {
    textAlign: 'right' as const,
    color: '#cbd5e1',
    fontSize: '12px',
  },
  chart: {
    width: '100%',
    height: '110px',
    display: 'block',
  },
  empty: {
    textAlign: 'center' as const,
    padding: '48px',
    color: '#666',
  },
  copyButton: {
    padding: '4px 8px',
    background: '#333',
    border: 'none',
    borderRadius: '4px',
    color: '#888',
    cursor: 'pointer',
    fontSize: '11px',
  },
  toast: {
    position: 'fixed' as const,
    bottom: '24px',
    right: '24px',
    background: '#22c55e',
    color: '#fff',
    padding: '12px 20px',
    borderRadius: '8px',
    fontSize: '14px',
    zIndex: 2000,
    animation: 'fadeIn 0.2s ease',
  },
};
